# Homework 1: Machine Learning Zoomcamp

## Q1. Pandas version
Checking the installed version of the Pandas library.

In [2]:
import pandas as pd

In [4]:
pd.__version__

'2.2.3'

## Getting the data
Downloading the `car_fuel_efficiency_2026.csv` dataset and reading it.

In [5]:
!wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

--2026-09-29 18:56:27--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘car_fuel_efficiency_2026.csv’

car_fuel_efficiency 100%[===================>] 620.29K  --.-KB/s    in 0.007s

2026-09-29 18:56:27 (87.8 MB/s) - ‘car_fuel_efficiency_2026.csv’ saved [635180/635180]

In [7]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

## Q2. Records count
Counting the total number of records (rows) in our dataset.

In [ ]:
df.shape

(10000, 11)

## Q3. Fuel types
Finding how many unique fuel types are present in the dataset.

In [10]:
df['fuel_type'].nunique()

3

## Q4. Missing values
Checking how many columns in our dataset have missing values (NaN/null).

In [12]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

## Q5. Max fuel efficiency
Finding the maximum fuel efficiency for cars manufactured in Asia (origin == 'Asia').

In [13]:
df['fuel_efficiency_mpg'].max()

41.2

## Q6. Median value of horsepower
1. Знаходимо медіану для колонки `horsepower`.
2. Знаходимо найчастіше значення (моду) для цієї ж колонки.
3. Заповнюємо пропуски модою.
4. Знову рахуємо медіану і перевіряємо, чи змінилася вона.

In [ ]:
df['horsepower'].median()

254.0

In [19]:
df['horsepower'].value_counts()
df['horsepower'].mode()[0]

np.float64(252.0)

In [23]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode()[0])

In [24]:
df['horsepower'].median()

252.0

## Q7. Sum of weights (Matrix Operations)
1. Відбираємо всі авто з Азії.
2. Залишаємо колонки `vehicle_weight` та `model_year`.
3. Беремо перші 7 значень і перетворюємо їх у масив NumPy `X`.
4. Знаходимо матрицю `XTX` (множення `X.T` на `X`), а потім її обернену матрицю.

In [30]:
df_Asia = df[df['origin'] == 'Asia']
df_Asia.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [35]:
df_2 = df_Asia[['vehicle_weight', 'model_year']]
df_2.head()

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007

In [40]:
df_2.iloc[:7]

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [41]:
import numpy as np

In [48]:
X = np.array(df_2.iloc[:7])
X.shape

(7, 2)

In [49]:
XTX = X.T.dot(X)
XTX.shape

(2, 2)

In [53]:
XTX_inv = np.linalg.inv(XTX)

In [ ]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [56]:
w = XTX_inv@X.T@y
w

array([0.13644777, 0.2327492 ])

In [57]:
w.sum()

np.float64(0.36919696904925486)